/* eslint-disable import/extensions */
/* eslint-disable import/no-unresolved */
/* eslint-disable no-undef */
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './styles/globals.css';
import React from 'react';
import { MSWComponent } from '@/mocks/MSWComponent';
import MusicBar from './components/Musicbar/Musicbar';
import NavigationBar from './components/NavBar/NavigationBar';
import QueryProviders from './components/QueryProvider/QueryProvider';
import { SharedAudioProvider } from './components/audio/Audio';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'DreamVault',
  description: 'Generated by 별이 빛나는 밤',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <link
          rel="icon"
          href="https://i.ibb.co/1GnSm8z/Dream-Vault-Png.png"
          sizes="any"
        />
        <MSWComponent>
          <QueryProviders>
            <SharedAudioProvider>
              {children}
              <MusicBar />
            </SharedAudioProvider>
            <NavigationBar />
          </QueryProviders>
        </MSWComponent>
      </body>
    </html>
  );
}
