/* eslint-disable import/no-unresolved */
/* eslint-disable camelcase */
/* eslint-disable import/prefer-default-export */
/* eslint-disable import/no-extraneous-dependencies */
/* eslint-disable arrow-body-style */
import { HttpResponse, http } from 'msw';

export const searchHandlers = [
  http.get('/api/v1/search', () => {
    return HttpResponse.json({
      status: 'success',
      data: {
        results: [
          {
            track_id: 2,
            title: 'Harmonic Horizon',
            uploader_name: 'Minseok',
            genre_name: 'Ambient <em>AI</em>', // 이 이분 강조됨
            thumbnail_image: 'url/to/thumbnail1.com',
            prompt:
              'A journey through soundscapes generated by <em>AI</em>, capturing the essence of a horizon where digital meets', // 이 이분 강조됨
            tags: 'explorative / organic / digital',
          },
          {
            track_id: 2,
            title: 'Retrograde Motion',
            uploader_name: 'Sam Walton',
            genre_name: '<em>AI</em> Pop', // 이 이분 강조됨
            thumbnail_image: 'url/to/thumbnail2.com',
            prompt:
              'Travel back in time with retro synths and futuristic beats, blending past and future in a melodious dance.',
            tags: 'retro / futuristic',
          },
          // Additional search results...
        ],
        page_info: {
          page: 1,
          size: 20,
          total_elements: 95,
          total_pages: 5,
        },
      },
      message: 'Search results retrieved successfully.',
    });
  }),
];
